-- ==========================================
-- Fintax Mitra Database Schema for Supabase
-- Run this in the Supabase SQL Editor
-- ==========================================

-- 1. Create Clients Table
CREATE TABLE public.clients (
    pan TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    biz TEXT,
    mob TEXT,
    email TEXT,
    gstin TEXT,
    addr TEXT,
    state TEXT,
    type TEXT,
    src TEXT,
    added TEXT,
    status TEXT DEFAULT 'Active',
    note TEXT,
    aadhaar TEXT,
    dob TEXT,
    "fatherName" TEXT,
    gender TEXT,
    "residentialStatus" TEXT,
    pin TEXT,
    "bankName" TEXT,
    ifsc TEXT,
    "accountNumber" TEXT,
    "itrType" TEXT,
    "extraPw" JSONB DEFAULT '[]'::jsonb,
    portals JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Works Table
CREATE TABLE public.works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pan TEXT REFERENCES public.clients(pan) ON DELETE CASCADE,
    cn TEXT NOT NULL,
    svc TEXT,
    fy TEXT,
    due TEXT,
    staff TEXT,
    status TEXT,
    fees NUMERIC DEFAULT 0,
    comm NUMERIC DEFAULT 0,
    rcvd NUMERIC DEFAULT 0,
    src TEXT,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Invoices Table
CREATE TABLE public.invoices (
    id TEXT PRIMARY KEY, -- e.g., INV-2025-001
    date TEXT NOT NULL,
    pan TEXT REFERENCES public.clients(pan) ON DELETE CASCADE,
    "clientName" TEXT NOT NULL,
    "workId" BIGINT REFERENCES public.works(id) ON DELETE SET NULL,
    service TEXT,
    fy TEXT,
    amount NUMERIC DEFAULT 0,
    gst NUMERIC DEFAULT 0,
    "gstAmt" NUMERIC DEFAULT 0,
    "subTotal" NUMERIC DEFAULT 0,
    discount NUMERIC DEFAULT 0,
    items JSONB DEFAULT '[]'::jsonb,
    total NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Unpaid',
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Receipts Table
CREATE TABLE public.receipts (
    id TEXT PRIMARY KEY, -- e.g., RCP-001
    date TEXT NOT NULL,
    "invId" TEXT REFERENCES public.invoices(id) ON DELETE CASCADE,
    pan TEXT REFERENCES public.clients(pan) ON DELETE CASCADE,
    "clientName" TEXT NOT NULL,
    "invAmt" NUMERIC DEFAULT 0,
    received NUMERIC DEFAULT 0,
    mode TEXT,
    ref TEXT,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Computations Table
CREATE TABLE public.computations (
    id TEXT PRIMARY KEY,
    fy TEXT NOT NULL,
    pan TEXT REFERENCES public.clients(pan) ON DELETE CASCADE,
    name TEXT NOT NULL,
    assessee JSONB NOT NULL,
    income JSONB NOT NULL,
    deductions JSONB NOT NULL,
    "manualDeductions" JSONB DEFAULT '[]'::jsonb,
    "taxPaid" JSONB NOT NULL,
    "printRegime" TEXT DEFAULT 'new',
    "savedAt" BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create Firm Settings Table (Singleton)
CREATE TABLE public.firm_settings (
    id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    settings JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Create Developer Settings Table (Singleton)
CREATE TABLE public.developer_settings (
    id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    dropdown_defaults JSONB NOT NULL,
    passwords JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- Enable Row Level Security (RLS) on all
-- ==========================================
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.works ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.computations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.firm_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.developer_settings ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- Create Security Policies (Only Authenticated Admins)
-- ==========================================
CREATE POLICY "Admin CRUD on clients" ON public.clients FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD on works" ON public.works FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD on invoices" ON public.invoices FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD on receipts" ON public.receipts FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD on computations" ON public.computations FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD on firm_settings" ON public.firm_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD on developer_settings" ON public.developer_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
